---
title: "Code used in project: Metagenome analysis of soil-dwelling bacterial decomposers following long-term warming using a reference genome approach"
author: "Seojin Jung"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following directory contains HTML files outlining the code used to generate the results presented in Seojin Jung's senior thesis in Biology at Amherst College, "Metagenome analysis of soil-dwelling bacterial decomposers following long-term warming using a reference genome approach." The main repository is [here](https://github.com/OurMicrobiome/seojin_thesis).

# HTML files
* [Setting up in RStudio](setup.html)
* [Generating Sankey plot](mag_taxonomy_sankey.html)
* [MetaBAT analyses]()
* [Extract traits and build matrices]()
* [Trait selection and processing]()
* [Problematic classification of decomposers]()
* [Hierarchical clustering and heatmap]()
* [Differential abundance analysis]()

# Images/figures
* [Interactive HTML file with Pavian Sankey Plot for BW filter metagenomes](sankey-BW_coassembly_GTDB_pavian.html)

# Miscellaneous code not included in main work
* [Counts of MAGs per trait]()
* [Initial guild clustering]()